# Thiss is a basic workflow to help you get started with Actions

name: environment-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # "build" job
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
    # Compile
      - name: Compile
        run: echo "Compiling the code"
  
  # Deployment to Development environment     
  DeployDev:
      name: Deploy to Dev
      if: github.event_name == 'pull_request'
      needs: [Build]
      runs-on: ubuntu-latest
      environment:
        name: Development
        url: 'http://dev.mcsapp.com'
      steps:
        - name: Deploy
          run: echo "Deploying the code in dev environment"

# Deploying Staging environment
  DeployStaging:
      name: Deploy to Staging
      if: github.event.ref == 'refs/heads/main'
      needs: [Build]
      runs-on: ubuntu-latest
      environment:
        name: Staging
        url: 'http://stg.mcsapp.com'
      steps:
        - name: Deploy
          run: echo "Deploying the code in staging environment"
          
# Deploying to Production environment        
  DeployProd:
      name: Deploy to Prod
      needs: [DeployStaging]
      runs-on: ubuntu-latest
      environment:
        name: Production
        url: 'http://prod.mcsapp.com'
      steps:
        - name: Deploy
          run: echo "Deploying the code in production environment"
          
      
  
